name: ci_game

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "game/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unity - Request Activation File
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      # - name: Unity - Builder
      #   uses: game-ci/unity-builder@v2.0-alpha-6
      #   with:
      #     targetPlatform: "WebGL"
      #     projectPath: "game"
