name: ci_game

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "game/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: "android"
          projectPath: "game"
